# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: 23
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Download
        path: ./target/*.jar
